document.querySelectorAll(".no09").forEach(function (content) { content.textContent = "daydream" })
document.querySelectorAll(".no19").forEach(function (content) { content.textContent = "都怨你" })
document.querySelectorAll(".no23").forEach(function (content) { content.textContent = "L." })
document.querySelectorAll(".no25").forEach(function (content) { content.textContent = "￴￴ ￴￴ ￴" })
document.querySelectorAll(".no26").forEach(function (content) { content.textContent = "IRieNnE" })